[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[eventlistener:multivisor-rpc]
command=multivisor-rpc --bind 0.0.0.0:9002
events=PROCESS_STATE,SUPERVISOR_STATE_CHANGE
buffer_size=100

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile
autostart=false
autorestart=true
stderr_logfile=/var/log/supervisor/caddy.err.log
stdout_logfile=/var/log/supervisor/caddy.out.log