name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true

jobs:
  deploy:
    runs-on: [ self-hosted, ubuntu-4gb-hel1-1 ]
    environment: production
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Cleanup Docker
        run: |
          docker builder prune -f

      - name: Build .env
        env:
          ENV_FILE: ${{ vars.ENV_FILE }}
        run: |
          echo "$ENV_FILE" | sed 's/\r//' > .devcontainer/mapped/.env

      - name: Deploy
        run: |
          set -euo pipefail
          cd .devcontainer/mapped
          echo "DOCKER_UID=$(id -u)" >> .env
          echo "DOCKER_GID=$(id -g)" >> .env
          docker compose down
          docker compose up --build -d --wait
          bash cmd-run.sh
